# -*- coding: utf-8 -*-
"""DocumentAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146rpd6oDhYtO3nDmUHHudVRWk1fb0PaO
"""


import os
from groq import Groq

api_key = os.getenv("GROQ_API_KEY")

client = Groq(
    api_key=os.environ["GROQ_API_KEY"]
)

LLM_MODEL = "llama-3.3-70b-versatile"

print("Groq client ready.")

import os, re, json, pickle
import numpy as np
import pandas as pd

from pypdf import PdfReader
import docx
import language_tool_python

from sentence_transformers import SentenceTransformer
import faiss


# ==========================================================
# IMPORTANT: GROQ SETUP IS IN YOUR OTHER CELL
# This code expects:
#   - a global variable named `client`
#   - model name in `LLM_MODEL`
# Example in your Groq cell:
#   from groq import Groq
#   client = Groq(api_key=os.environ["GROQ_API_KEY"])
#   LLM_MODEL = "llama-3.3-70b-versatile"
# ==========================================================

# =========================
# CONFIG
# =========================
EMBED_MODEL = "all-MiniLM-L6-v2"
UNI_EMB_PKL = "uni_embeddings.pkl"
PROG_EMB_PKL = "program_embeddings.pkl"

embedder = SentenceTransformer(EMBED_MODEL)
lt_tool = language_tool_python.LanguageTool("en-US")

# FIX 1: Expanded stoplist to remove URL fragments, noise, and generic words
KEYWORD_STOPLIST = {
    # Generic words
    "the","and","for","with","this","that","from","your","have","will","you","our","are","can","also",
    "program","university","department","students","course","courses","study","research","faculty",
    "requirements","requirement","application","admission","deadline","tuition","fees","location",
    "more","information","please","visit","contact","email","phone","address","apply","online",
    "full","time","part","per","year","credit","hours","minimum","maximum","based","must","meet",
    "all","any","one","two","three","four","five","six","seven","eight","nine","ten",
    "not","but","its","has","was","been","they","their","them","who","what","when","where","how",
    "each","which","about","after","before","during","other","into","than","then","some","only",
    "may","use","used","new","also","both","well","even","such","same","most","many","best",
    # URL fragments — FIX for "http", "https", "www", "adance" etc.
    "http","https","www","html","php","asp","aspx","edu","com","org","net","gov","htm",
    # Common garbage tokens from scraped CSV data
    "nan","none","null","true","false","yes","no",
}


# =========================
# SAFE JSON PARSE
# =========================
def safe_json_parse(text: str) -> dict:
    if text is None:
        return {"error": "empty_response"}

    t = text.strip()

    # Remove markdown fences if present
    if t.startswith("```"):
        t = re.sub(r"^```[a-zA-Z]*\s*", "", t)
        t = re.sub(r"\s*```$", "", t).strip()

    # Try direct JSON
    try:
        return json.loads(t)
    except:
        # Try to isolate the first JSON object
        m = re.search(r"\{.*\}", t, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except:
                pass

    return {"error": "invalid_json", "raw": text[:4000]}


# =========================
# LLM CALL (expects global `client`, `LLM_MODEL`)
# =========================
def ask_llm_json(prompt: str, max_tokens: int = 2500, temperature: float = 0.0) -> dict:
    if "client" not in globals():
        raise RuntimeError("Groq client not found. Define `client = Groq(...)` in a separate cell first.")
    if "LLM_MODEL" not in globals():
        raise RuntimeError("LLM_MODEL not found. Define `LLM_MODEL = ...` in your Groq cell first.")

    r = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        max_tokens=max_tokens
    )
    return safe_json_parse(r.choices[0].message.content)


# =========================
# READ DOCUMENT
# =========================
def read_pdf(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join([(p.extract_text() or "") for p in reader.pages]).strip()

def read_docx(path: str) -> str:
    d = docx.Document(path)
    return "\n".join([p.text for p in d.paragraphs]).strip()

def read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

def read_document(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".pdf":
        return read_pdf(path)
    if ext == ".docx":
        return read_docx(path)
    if ext == ".txt":
        return read_txt(path)
    raise ValueError("Unsupported file type (.pdf/.docx/.txt)")


# =========================
# LOAD + EMBEDDINGS + FAISS
# =========================
def load_data(university_csv: str, program_csv: str):
    unis = pd.read_csv(university_csv)
    progs = pd.read_csv(program_csv)

    unis["combined"] = unis.fillna("").astype(str).agg(" | ".join, axis=1)
    progs["combined"] = progs.fillna("").astype(str).agg(" | ".join, axis=1)

    return unis, progs

def build_index(df: pd.DataFrame, text_col: str, pkl_path: str):
    texts = df[text_col].fillna("").astype(str).tolist()

    if os.path.exists(pkl_path):
        with open(pkl_path, "rb") as f:
            emb = pickle.load(f)
        emb = np.array(emb, dtype="float32")
    else:
        emb = embedder.encode(texts, normalize_embeddings=True)
        emb = np.array(emb, dtype="float32")
        with open(pkl_path, "wb") as f:
            pickle.dump(emb, f)

    index = faiss.IndexFlatIP(emb.shape[1])
    index.add(emb)
    return index

def retrieve(df: pd.DataFrame, index, query: str, k: int = 3) -> pd.DataFrame:
    q = embedder.encode([query], normalize_embeddings=True).astype("float32")
    D, I = index.search(q, k)
    out = df.iloc[I[0]].copy()
    out["score"] = D[0]
    return out


# =========================
# GRAMMAR CHECK
# =========================
def grammar_check(text: str, max_issues: int = 25) -> dict:
    matches = lt_tool.check(text)
    corrected = language_tool_python.utils.correct(text, matches)

    issues = []
    for m in matches[:max_issues]:
        issues.append({
            "message": m.message,
            "context": m.context,
            "replacements": m.replacements[:5]
        })

    # FIX 2: Compute a 0-100 grammar quality score (higher = fewer issues, better quality)
    # Penalise ~2 points per issue, floor at 0
    issue_count = len(matches)
    grammar_quality_score = max(0, 100 - issue_count * 2)

    return {
        "count": issue_count,                        # raw issue count (e.g. 22)
        "grammar_quality_score": grammar_quality_score,  # 0-100 quality score (e.g. 56)
        "issues": issues,
        "corrected": corrected
    }


# =========================
# CLASSIFY DOC TYPE (LLM)
# =========================
def classify(text: str) -> dict:
    prompt = f"""
Return ONLY JSON.

Schema:
{{
  "doc_type":"SOP|RESUME",
  "confidence": 0.0,
  "reason_short":""
}}

TEXT:
{text[:6000]}
"""
    out = ask_llm_json(prompt, max_tokens=450)

    if "doc_type" not in out:
        out = {"doc_type": "RESUME" if "experience" in text.lower() else "SOP", "confidence": 0.5, "reason_short": "fallback"}
    return out


# =========================
# FORMAT CHECK
# FIX 3: Only evaluate sections relevant to the detected doc_type
# =========================
def format_check(text: str, doc_type: str) -> dict:
    lower = text.lower()
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    first_para = lines[0] if lines else ""

    checks = {}

    if doc_type == "RESUME":
        # Only check resume sections for a RESUME doc
        checks["resume_header"]     = bool(re.search(r"\bemail\b|@\w+|\bphone\b|\bmobile\b|\blinkedin\b|\bgithub\b", text, re.I))
        checks["resume_education"]  = bool(re.search(r"\beducation\b|\bdegree\b|\buniversity\b|\bcgpa\b|\bgpa\b", text, re.I))
        checks["resume_experience"] = bool(re.search(r"\bexperience\b|\bemployment\b|\bwork history\b", text, re.I))
        checks["resume_projects"]   = bool(re.search(r"\bprojects?\b|\bportfolio\b", text, re.I))
        checks["resume_skills"]     = bool(re.search(r"\bskills?\b|\btechnologies\b|\btools\b", text, re.I))
        checks["resume_extras"]     = bool(re.search(r"\bcertifications?\b|\bawards?\b|\bvolunteer\b|\bleadership\b", text, re.I))

        required = ["resume_header", "resume_education", "resume_experience", "resume_skills"]

    else:
        # Only check SOP sections for an SOP doc
        checks["sop_intro"]          = (
            "statement of purpose" in lower
            or "i am applying" in lower
            or "i wish to pursue" in lower
            or len(first_para) > 50
        )
        checks["sop_academics"]      = bool(re.search(r"\b(bachelor|undergraduate|degree|cgpa|gpa|university)\b", lower))
        checks["sop_experience"]     = bool(re.search(r"\b(intern|internship|project|research|work experience)\b", lower))
        checks["sop_why_program"]    = bool(re.search(r"\b(program|curriculum|courses|specialization|research interests)\b", lower))
        checks["sop_why_university"] = bool(re.search(r"\b(university|faculty|lab|research group|department)\b", lower))
        checks["sop_goals"]          = bool(re.search(r"\b(career goals?|short[- ]term|long[- ]term|i aim to|i plan to|aspire)\b", lower))
        checks["sop_conclusion"]     = bool(re.search(r"\b(in conclusion|thank you|i look forward|i would be honored|i am confident)\b", lower))

        required = ["sop_intro", "sop_academics", "sop_experience", "sop_goals"]

    missing = [r for r in required if not checks.get(r)]

    # Also flag optional-but-important missing sections
    if doc_type == "RESUME" and not checks.get("resume_projects"):
        missing.append("resume_projects")
    if doc_type == "SOP" and not checks.get("sop_conclusion"):
        missing.append("sop_conclusion")

    return {
        "is_correct_format": (len(missing) == 0),
        "missing_sections": missing,
        "section_checks": checks
    }


# =========================
# CONTEXT BUILDER
# =========================
def build_context(unis, progs, uni_index, prog_index, uni, prog):
    q = f"{uni} {prog}".strip()
    u = retrieve(unis, uni_index, q, k=3)
    p = retrieve(progs, prog_index, q, k=3)
    return "\n".join(list(u["combined"]) + list(p["combined"]))


# =========================
# PROGRAM KEYWORDS (FROM CONTEXT)
# FIX 4: Strip URLs and noise tokens before ranking keywords
# =========================
def extract_program_keywords(context: str, top_k: int = 30) -> list:
    # Remove full URLs first so fragments like "adance" from "advancedcomputinginstitute" don't slip through
    context_clean = re.sub(r"https?://\S+", " ", context)
    context_clean = re.sub(r"www\.\S+", " ", context_clean)

    # Extract only alphabetic tokens of length >= 4 (avoids "www", "http", 3-letter noise)
    words = re.findall(r"[a-zA-Z]{4,}", context_clean.lower())

    # Filter against expanded stoplist
    words = [w for w in words if w not in KEYWORD_STOPLIST and not w.isdigit()]

    freq = {}
    for w in words:
        freq[w] = freq.get(w, 0) + 1

    sorted_words = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    return [w for w, _ in sorted_words[:top_k]]


def program_fit_score(text: str, context: str) -> dict:
    tl = text.lower()
    kws = extract_program_keywords(context, top_k=30)

    hits = [k for k in kws if k in tl]
    missing = [k for k in kws if k not in tl]

    score = min(100, int(len(hits) * (100 / max(1, len(kws)))))

    return {
        "program_fit_score": score,
        "matched_keywords": hits[:25],
        "missing_keywords": missing[:25],
        "keywords_used": kws
    }


# =========================
# ATS RESUME SCORING (PROGRAM-SPECIFIC)
# =========================
ACTION_VERBS = [
    "led","developed","implemented","designed","built","optimized","created",
    "managed","analyzed","improved","increased","reduced","delivered","automated",
    "coordinated","executed","launched","engineered","refactored","deployed","integrated"
]

def ats_score(text: str, context: str, fmt: dict) -> dict:
    tl = text.lower()
    program_keywords = extract_program_keywords(context, top_k=30)

    section_score = 0
    section_score += 10 if fmt["section_checks"].get("resume_header") else 0
    section_score += 15 if fmt["section_checks"].get("resume_education") else 0
    section_score += 15 if fmt["section_checks"].get("resume_experience") else 0
    section_score += 10 if fmt["section_checks"].get("resume_skills") else 0
    section_score += 5  if fmt["section_checks"].get("resume_projects") else 0
    section_score = min(section_score, 50)

    verb_count = sum(1 for v in ACTION_VERBS if v in tl)
    verb_score = min(15, verb_count * 2)

    metrics = len(re.findall(r"\b\d+(\.\d+)?\s*(%|x|yrs|years|months|users|clients|requests|ms|s)\b", tl))
    metric_score = min(15, metrics * 5)

    bullets = len(re.findall(r"(\n\s*[-•*]\s+)", text))
    bullet_score = min(10, bullets)

    prog_hits = sum(1 for k in program_keywords if k in tl)
    prog_kw_score = min(20, prog_hits * 2)

    total = int(min(100, section_score + verb_score + metric_score + bullet_score + prog_kw_score))

    suggestions = []
    if not fmt["section_checks"].get("resume_projects"):
        suggestions.append("Add a 'Projects' section with 2–3 program-relevant projects (2–4 bullets each).")
    if metrics == 0:
        suggestions.append("Add measurable impact (%, time saved, scale, users, requests) in bullets.")
    if verb_count < 4:
        suggestions.append("Start bullets with strong action verbs (Developed, Implemented, Optimized, Led).")
    if bullets < 5:
        suggestions.append("Convert paragraphs into concise bullet points (ATS prefers bullets).")
    if prog_hits < 4:
        suggestions.append("Add program-specific keywords and technical skills aligned with the selected program.")

    return {
        "ats_score": total,
        "breakdown": {
            "section_score": section_score,
            "action_verbs": {"count": verb_count, "score": verb_score},
            "metrics": {"count": metrics, "score": metric_score},
            "bullets": {"count": bullets, "score": bullet_score},
            "program_keywords": {"hits": prog_hits, "score": prog_kw_score, "sample": program_keywords[:12]},
        },
        "suggestions": suggestions
    }


# =========================
# LLM EVALUATION + REWRITE
# =========================
def evaluate_and_rewrite(
    text,
    corrected,
    doc_type,
    format_report,
    grammar_report,
    context,
    program_fit,
    uni_name,
    prog_name,
    ats_report=None
):
    if doc_type == "RESUME":
        structure_rules = """
STRICT RESUME RULES:
- MUST be ATS-friendly.
- Use EXACT headings (in order):
  NAME + CONTACT
  PROFESSIONAL SUMMARY
  SKILLS (must be aligned to target program)
  EXPERIENCE
  EDUCATION
  PROJECTS (MUST ADD if missing; use [ADD DETAIL] if needed)
  ADDITIONAL (optional)
- Experience & Projects MUST be bullet points.
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten resume MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""
    else:
        structure_rules = """
STRICT SOP RULES:
- Use EXACT headings (in order):
  Introduction
  Academic Background
  Experience and Projects
  Why This Program
  Why This University
  Career Goals
  Conclusion
- No bullet lists (use paragraphs).
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten SOP MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""

    ats_block = ""
    if ats_report is not None:
        ats_block = f"\nATS_REPORT:\n{json.dumps(ats_report, ensure_ascii=False)}\n"

    # FIX 5: Pass grammar_quality_score (0-100) to LLM, not raw issue count
    grammar_summary = {
        "issue_count": grammar_report["count"],
        "quality_score_0_to_100": grammar_report["grammar_quality_score"],
        "top_issues": [i["message"] for i in grammar_report["issues"][:10]]
    }

    prompt = f"""
You are an admissions reviewer and writing coach.

Return ONLY valid JSON. No markdown. No triple backticks.

TARGET UNIVERSITY: {uni_name}
TARGET PROGRAM: {prog_name}

{structure_rules}

UNIVERSITY+PROGRAM CONTEXT (from dataset):
{context}

PROGRAM_FIT (keyword-based):
{json.dumps(program_fit, ensure_ascii=False)}

FORMAT_REPORT (rule-based):
{json.dumps(format_report, ensure_ascii=False)}

GRAMMAR_REPORT:
{json.dumps(grammar_summary, ensure_ascii=False)}
{ats_block}

DOCUMENT (grammar-corrected):
{corrected[:12000]}

Return JSON in this exact schema (match keys exactly):

{{
  "doc_type": "{doc_type}",
  "overall_score": 0,
  "overall_quality_label": "Very Weak|Weak|Average|Strong|Exceptional",

  "program_specificity": {{
    "target_university": "{uni_name}",
    "target_program": "{prog_name}",
    "fit_score": 0,
    "missing_keywords_to_add": [],
    "where_to_add_keywords": []
  }},

  "format_and_sections": {{
    "is_correct_format": false,
    "missing_sections": [],
    "section_checks": {{}}
  }},

  "grammar": {{
    "score": 0,
    "top_issues": []
  }},

  "clarity": {{
    "score": 0,
    "issues": []
  }},

  "tone": {{
    "summary": "",
    "is_appropriate": true,
    "issues": []
  }},

  "relevance_to_selected_program": {{
    "score": 0,
    "issues": [],
    "what_to_add_based_on_context": []
  }},

  "strengths": [],
  "weaknesses": [],

  "sentence_level_improvements": [
    {{
      "original": "",
      "improved": "",
      "why": ""
    }}
  ],

  "rewrite_output": {{
    "improved_document": ""
  }},

  "action_plan_next_revision": []
}}
"""
    out = ask_llm_json(prompt, max_tokens=3200, temperature=0.0)

    if isinstance(out, dict) and "error" not in out:
        # Inject rule-based format checks so they don't drift
        out.setdefault("format_and_sections", {})
        out["format_and_sections"]["is_correct_format"] = format_report["is_correct_format"]
        out["format_and_sections"]["missing_sections"] = format_report["missing_sections"]
        out["format_and_sections"]["section_checks"] = format_report["section_checks"]

        # Inject program fit as baseline
        out.setdefault("program_specificity", {})
        out["program_specificity"]["target_university"] = uni_name
        out["program_specificity"]["target_program"] = prog_name
        out["program_specificity"]["fit_score"] = program_fit.get("program_fit_score", 0)
        out["program_specificity"]["missing_keywords_to_add"] = program_fit.get("missing_keywords", [])[:12]

        # FIX 6: Override grammar score with our computed quality score so it's consistent
        out.setdefault("grammar", {})
        out["grammar"]["score"] = grammar_report["grammar_quality_score"]
        out["grammar"]["issue_count"] = grammar_report["count"]

    return out


# =========================
# SAVE OUTPUT
# FIX 7: Save full structured report + rewrite in one readable file
# =========================
def save_output(result: dict, out_path: str = "improved_document.txt"):
    lines = []

    ev = result.get("evaluation", {})
    doc_type = result.get("classification", {}).get("doc_type", "DOCUMENT")

    lines.append("=" * 60)
    lines.append(f"  DOCUMENT ANALYSIS REPORT — {doc_type}")
    lines.append("=" * 60)

    # Scores summary
    lines.append("\n📊 SCORES SUMMARY")
    lines.append("-" * 40)
    lines.append(f"  Overall Score      : {ev.get('overall_score', 'N/A')} / 100")
    lines.append(f"  Quality Label      : {ev.get('overall_quality_label', 'N/A')}")

    grammar = ev.get("grammar", {})
    lines.append(f"  Grammar Score      : {grammar.get('score', 'N/A')} / 100  ({result['grammar']['count']} issues found)")

    prog_spec = ev.get("program_specificity", {})
    lines.append(f"  Program Fit Score  : {prog_spec.get('fit_score', 'N/A')} / 100")

    if result.get("ats_score"):
        lines.append(f"  ATS Score          : {result['ats_score']['ats_score']} / 100")

    clarity = ev.get("clarity", {})
    lines.append(f"  Clarity Score      : {clarity.get('score', 'N/A')} / 100")

    relevance = ev.get("relevance_to_selected_program", {})
    lines.append(f"  Program Relevance  : {relevance.get('score', 'N/A')} / 100")

    # Format
    lines.append("\n📋 FORMAT CHECK")
    lines.append("-" * 40)
    fmt = ev.get("format_and_sections", {})
    lines.append(f"  Correct Format     : {fmt.get('is_correct_format', 'N/A')}")
    missing = fmt.get("missing_sections", [])
    lines.append(f"  Missing Sections   : {missing if missing else 'None'}")

    # Strengths / Weaknesses
    lines.append("\n✅ STRENGTHS")
    lines.append("-" * 40)
    for s in ev.get("strengths", []) or ["None identified"]:
        lines.append(f"  • {s}")

    lines.append("\n❌ WEAKNESSES")
    lines.append("-" * 40)
    for w in ev.get("weaknesses", []) or ["None identified"]:
        lines.append(f"  • {w}")

    # Grammar issues
    lines.append("\n🔤 TOP GRAMMAR ISSUES")
    lines.append("-" * 40)
    for issue in grammar.get("top_issues", [])[:5]:
        lines.append(f"  • {issue}")

    # Keywords
    lines.append("\n🔑 MISSING PROGRAM KEYWORDS")
    lines.append("-" * 40)
    missing_kws = prog_spec.get("missing_keywords_to_add", [])
    lines.append(f"  {', '.join(missing_kws) if missing_kws else 'None'}")
    lines.append(f"  Add in: {', '.join(prog_spec.get('where_to_add_keywords', []))}")

    # ATS suggestions
    if result.get("ats_score"):
        lines.append("\n🤖 ATS SUGGESTIONS")
        lines.append("-" * 40)
        for sug in result["ats_score"].get("suggestions", []):
            lines.append(f"  • {sug}")

    # Sentence improvements
    lines.append("\n✏️  SENTENCE-LEVEL IMPROVEMENTS")
    lines.append("-" * 40)
    for imp in (ev.get("sentence_level_improvements") or [])[:5]:
        if imp.get("original"):
            lines.append(f"  BEFORE : {imp['original']}")
            lines.append(f"  AFTER  : {imp['improved']}")
            lines.append(f"  WHY    : {imp['why']}")
            lines.append("")

    # Action plan
    lines.append("\n📌 ACTION PLAN FOR NEXT REVISION")
    lines.append("-" * 40)
    for step in (ev.get("action_plan_next_revision") or []):
        lines.append(f"  • {step}")

    # Rewritten document
    lines.append("\n" + "=" * 60)
    lines.append("  REWRITTEN DOCUMENT")
    lines.append("=" * 60 + "\n")

    improved = ""
    ro = ev.get("rewrite_output", {})
    if isinstance(ro, dict):
        improved = ro.get("improved_document", "") or ""

    if isinstance(improved, str):
        s = improved.strip()
        try:
            parsed = json.loads(s)
            if isinstance(parsed, dict):
                parts = []
                for k, v in parsed.items():
                    parts.append(k.upper())
                    parts.append("-" * len(k))
                    parts.append("")
                    parts.append(str(v))
                    parts.append("\n")
                improved = "\n".join(parts).strip()
        except:
            pass

    lines.append(improved.strip() if improved.strip() else "No rewrite generated.")

    full_output = "\n".join(lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(full_output)

    print(f"✅ Saved report to: {out_path}")
    return full_output


# =========================
# PRINT SUMMARY (clean terminal output)
# FIX 8: Clean summary print — no truncated JSON dumps
# =========================
def print_summary(result: dict):
    ev = result.get("evaluation", {})
    classification = result.get("classification", {})

    print("\n" + "=" * 55)
    print(f"  ANALYSIS SUMMARY")
    print("=" * 55)
    print(f"  Doc Type      : {classification.get('doc_type')}  (confidence: {classification.get('confidence')})")
    print(f"  Overall Score : {ev.get('overall_score', 'N/A')} / 100  [{ev.get('overall_quality_label', '')}]")
    print(f"  Grammar       : {result['grammar']['grammar_quality_score']} / 100  ({result['grammar']['count']} issues)")
    print(f"  Program Fit   : {result['program_fit']['program_fit_score']} / 100")

    if result.get("ats_score"):
        print(f"  ATS Score     : {result['ats_score']['ats_score']} / 100")

    fmt = result.get("format", {})
    missing_sections = fmt.get("missing_sections", [])
    print(f"  Missing Sects : {missing_sections if missing_sections else 'None'}")

    missing_kws = result["program_fit"].get("missing_keywords", [])[:8]
    print(f"  Missing KWs   : {missing_kws}")

    print("\n  Weaknesses:")
    for w in (ev.get("weaknesses") or []):
        print(f"    • {w}")

    if result.get("ats_score"):
        print("\n  ATS Suggestions:")
        for s in result["ats_score"].get("suggestions", []):
            print(f"    • {s}")

    print("=" * 55 + "\n")


# =========================
# MAIN PIPELINE
# =========================
def analyze(doc, uni, prog, uni_csv, prog_csv):
    text = read_document(doc)

    grammar = grammar_check(text)
    classification = classify(text)
    doc_type = classification.get("doc_type", "SOP")

    fmt = format_check(text, doc_type)

    unis, progs = load_data(uni_csv, prog_csv)
    uni_index = build_index(unis, "combined", UNI_EMB_PKL)
    prog_index = build_index(progs, "combined", PROG_EMB_PKL)

    context = build_context(unis, progs, uni_index, prog_index, uni, prog)

    prog_fit = program_fit_score(text, context)

    ats = None
    if doc_type == "RESUME":
        ats = ats_score(text, context, fmt)

    evaluation = evaluate_and_rewrite(
        text=text,
        corrected=grammar["corrected"],
        doc_type=doc_type,
        format_report=fmt,
        grammar_report=grammar,
        context=context,
        program_fit=prog_fit,
        uni_name=uni,
        prog_name=prog,
        ats_report=ats
    )

    return {
        "classification": classification,
        "grammar": grammar,
        "format": fmt,
        "program_fit": prog_fit,
        "ats_score": ats,
        "evaluation": evaluation
    }


print("✅ Ready: Fixed Program-specific Analyzer (SOP + Resume)")
print("   Fixes: URL noise in keywords | Grammar score (0-100) | Doc-type-only section checks | Clean report output")

# ── Run this cell after your Groq setup cell ──────────────────────────────────
import json

result = analyze(
    doc="input.pdf",
    uni="Boston University",
    prog="Computer Science",
    uni_csv="universities_profile_filled (1).csv",
    prog_csv="program_Scrape.csv"
)

# Clean summary in terminal (no truncated JSON blobs)
print_summary(result)

# Save full structured report + rewrite to file
save_output(result, "improved_document.txt")

import os, re, json, pickle
import numpy as np
import pandas as pd

from pypdf import PdfReader
import docx
import language_tool_python

from sentence_transformers import SentenceTransformer
import faiss


# ==========================================================
# IMPORTANT: GROQ SETUP IS IN YOUR OTHER CELL
# This code expects:
#   - a global variable named `client`
#   - model name in `LLM_MODEL`
# Example in your Groq cell:
#   from groq import Groq
#   client = Groq(api_key=os.environ["GROQ_API_KEY"])
#   LLM_MODEL = "llama-3.3-70b-versatile"
# ==========================================================

# =========================
# CONFIG
# =========================
EMBED_MODEL = "all-MiniLM-L6-v2"
UNI_EMB_PKL = "uni_embeddings.pkl"
PROG_EMB_PKL = "program_embeddings.pkl"

embedder = SentenceTransformer(EMBED_MODEL)
lt_tool = language_tool_python.LanguageTool("en-US")

# FIX 1: Expanded stoplist to remove URL fragments, noise, and generic words
KEYWORD_STOPLIST = {
    # Generic words
    "the","and","for","with","this","that","from","your","have","will","you","our","are","can","also",
    "program","university","department","students","course","courses","study","research","faculty",
    "requirements","requirement","application","admission","deadline","tuition","fees","location",
    "more","information","please","visit","contact","email","phone","address","apply","online",
    "full","time","part","per","year","credit","hours","minimum","maximum","based","must","meet",
    "all","any","one","two","three","four","five","six","seven","eight","nine","ten",
    "not","but","its","has","was","been","they","their","them","who","what","when","where","how",
    "each","which","about","after","before","during","other","into","than","then","some","only",
    "may","use","used","new","also","both","well","even","such","same","most","many","best",
    # URL fragments — FIX for "http", "https", "www", "adance" etc.
    "http","https","www","html","php","asp","aspx","edu","com","org","net","gov","htm",
    # Common garbage tokens from scraped CSV data
    "nan","none","null","true","false","yes","no",
    # Known garbage tokens observed in scraped CSV output
    "rolling","adance","january","advancedcomputinginstitute","institute","private","college",
    "academics","programs","computing",  # too generic to be useful signal
}


# =========================
# SAFE JSON PARSE
# =========================
def safe_json_parse(text: str) -> dict:
    if text is None:
        return {"error": "empty_response"}

    t = text.strip()

    # Remove markdown fences if present
    if t.startswith("```"):
        t = re.sub(r"^```[a-zA-Z]*\s*", "", t)
        t = re.sub(r"\s*```$", "", t).strip()

    # Try direct JSON
    try:
        return json.loads(t)
    except:
        # Try to isolate the first JSON object
        m = re.search(r"\{.*\}", t, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except:
                pass

    return {"error": "invalid_json", "raw": text[:4000]}


# =========================
# LLM CALL (expects global `client`, `LLM_MODEL`)
# =========================
def ask_llm_json(prompt: str, max_tokens: int = 2500, temperature: float = 0.0) -> dict:
    if "client" not in globals():
        raise RuntimeError("Groq client not found. Define `client = Groq(...)` in a separate cell first.")
    if "LLM_MODEL" not in globals():
        raise RuntimeError("LLM_MODEL not found. Define `LLM_MODEL = ...` in your Groq cell first.")

    r = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        max_tokens=max_tokens
    )
    return safe_json_parse(r.choices[0].message.content)


# =========================
# READ DOCUMENT
# =========================
def read_pdf(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join([(p.extract_text() or "") for p in reader.pages]).strip()

def read_docx(path: str) -> str:
    d = docx.Document(path)
    return "\n".join([p.text for p in d.paragraphs]).strip()

def read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

def read_document(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".pdf":
        return read_pdf(path)
    if ext == ".docx":
        return read_docx(path)
    if ext == ".txt":
        return read_txt(path)
    raise ValueError("Unsupported file type (.pdf/.docx/.txt)")


# =========================
# LOAD + EMBEDDINGS + FAISS
# =========================
def load_data(university_csv: str, program_csv: str):
    unis = pd.read_csv(university_csv)
    progs = pd.read_csv(program_csv)

    unis["combined"] = unis.fillna("").astype(str).agg(" | ".join, axis=1)
    progs["combined"] = progs.fillna("").astype(str).agg(" | ".join, axis=1)

    return unis, progs

def build_index(df: pd.DataFrame, text_col: str, pkl_path: str):
    texts = df[text_col].fillna("").astype(str).tolist()

    if os.path.exists(pkl_path):
        with open(pkl_path, "rb") as f:
            emb = pickle.load(f)
        emb = np.array(emb, dtype="float32")
    else:
        emb = embedder.encode(texts, normalize_embeddings=True)
        emb = np.array(emb, dtype="float32")
        with open(pkl_path, "wb") as f:
            pickle.dump(emb, f)

    index = faiss.IndexFlatIP(emb.shape[1])
    index.add(emb)
    return index

def retrieve(df: pd.DataFrame, index, query: str, k: int = 3) -> pd.DataFrame:
    q = embedder.encode([query], normalize_embeddings=True).astype("float32")
    D, I = index.search(q, k)
    out = df.iloc[I[0]].copy()
    out["score"] = D[0]
    return out


# =========================
# GRAMMAR CHECK
# =========================
def grammar_check(text: str, max_issues: int = 25) -> dict:
    matches = lt_tool.check(text)
    corrected = language_tool_python.utils.correct(text, matches)

    issues = []
    for m in matches[:max_issues]:
        issues.append({
            "message": m.message,
            "context": m.context,
            "replacements": m.replacements[:5]
        })

    # FIX 2: Compute a 0-100 grammar quality score (higher = fewer issues, better quality)
    # Penalise ~2 points per issue, floor at 0
    issue_count = len(matches)
    grammar_quality_score = max(0, 100 - issue_count * 2)

    return {
        "count": issue_count,                        # raw issue count (e.g. 22)
        "grammar_quality_score": grammar_quality_score,  # 0-100 quality score (e.g. 56)
        "issues": issues,
        "corrected": corrected
    }


# =========================
# CLASSIFY DOC TYPE (LLM)
# =========================
def classify(text: str) -> dict:
    prompt = f"""
Return ONLY JSON.

Schema:
{{
  "doc_type":"SOP|RESUME",
  "confidence": 0.0,
  "reason_short":""
}}

TEXT:
{text[:6000]}
"""
    out = ask_llm_json(prompt, max_tokens=450)

    if "doc_type" not in out:
        out = {"doc_type": "RESUME" if "experience" in text.lower() else "SOP", "confidence": 0.5, "reason_short": "fallback"}
    return out


# =========================
# FORMAT CHECK
# FIX 3: Only evaluate sections relevant to the detected doc_type
# =========================
def format_check(text: str, doc_type: str) -> dict:
    lower = text.lower()
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    first_para = lines[0] if lines else ""

    checks = {}

    if doc_type == "RESUME":
        # Only check resume sections for a RESUME doc
        checks["resume_header"]     = bool(re.search(r"\bemail\b|@\w+|\bphone\b|\bmobile\b|\blinkedin\b|\bgithub\b", text, re.I))
        checks["resume_education"]  = bool(re.search(r"\beducation\b|\bdegree\b|\buniversity\b|\bcgpa\b|\bgpa\b", text, re.I))
        checks["resume_experience"] = bool(re.search(r"\bexperience\b|\bemployment\b|\bwork history\b", text, re.I))
        checks["resume_projects"]   = bool(re.search(r"\bprojects?\b|\bportfolio\b", text, re.I))
        checks["resume_skills"]     = bool(re.search(r"\bskills?\b|\btechnologies\b|\btools\b", text, re.I))
        checks["resume_extras"]     = bool(re.search(r"\bcertifications?\b|\bawards?\b|\bvolunteer\b|\bleadership\b", text, re.I))

        required = ["resume_header", "resume_education", "resume_experience", "resume_skills"]

    else:
        # Only check SOP sections for an SOP doc
        checks["sop_intro"]          = (
            "statement of purpose" in lower
            or "i am applying" in lower
            or "i wish to pursue" in lower
            or len(first_para) > 50
        )
        checks["sop_academics"]      = bool(re.search(r"\b(bachelor|undergraduate|degree|cgpa|gpa|university)\b", lower))
        checks["sop_experience"]     = bool(re.search(r"\b(intern|internship|project|research|work experience)\b", lower))
        checks["sop_why_program"]    = bool(re.search(r"\b(program|curriculum|courses|specialization|research interests)\b", lower))
        checks["sop_why_university"] = bool(re.search(r"\b(university|faculty|lab|research group|department)\b", lower))
        checks["sop_goals"]          = bool(re.search(r"\b(career goals?|short[- ]term|long[- ]term|i aim to|i plan to|aspire)\b", lower))
        checks["sop_conclusion"]     = bool(re.search(r"\b(in conclusion|thank you|i look forward|i would be honored|i am confident)\b", lower))

        required = ["sop_intro", "sop_academics", "sop_experience", "sop_goals"]

    missing = [r for r in required if not checks.get(r)]

    # Also flag optional-but-important missing sections
    if doc_type == "RESUME" and not checks.get("resume_projects"):
        missing.append("resume_projects")
    if doc_type == "SOP" and not checks.get("sop_conclusion"):
        missing.append("sop_conclusion")

    return {
        "is_correct_format": (len(missing) == 0),
        "missing_sections": missing,
        "section_checks": checks
    }


# =========================
# CONTEXT BUILDER
# =========================
def build_context(unis, progs, uni_index, prog_index, uni, prog):
    q = f"{uni} {prog}".strip()
    u = retrieve(unis, uni_index, q, k=3)
    p = retrieve(progs, prog_index, q, k=3)
    return "\n".join(list(u["combined"]) + list(p["combined"]))


# =========================
# PROGRAM KEYWORDS (FROM CONTEXT)
# FIX 4: Strip URLs and noise tokens before ranking keywords
# =========================
def extract_program_keywords(context: str, top_k: int = 30) -> list:
    # Remove full URLs first so fragments like "adance" from "advancedcomputinginstitute" don't slip through
    context_clean = re.sub(r"https?://\S+", " ", context)
    context_clean = re.sub(r"www\.\S+", " ", context_clean)

    # Extract only alphabetic tokens of length >= 4 (avoids "www", "http", 3-letter noise)
    words = re.findall(r"[a-zA-Z]{4,}", context_clean.lower())

    # Filter against expanded stoplist
    words = [w for w in words if w not in KEYWORD_STOPLIST and not w.isdigit()]

    freq = {}
    for w in words:
        freq[w] = freq.get(w, 0) + 1

    # Only keep words that appear at least twice — filters one-off garbage tokens
    freq = {w: c for w, c in freq.items() if c >= 2}

    sorted_words = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    return [w for w, _ in sorted_words[:top_k]]


def program_fit_score(text: str, context: str) -> dict:
    tl = text.lower()
    kws = extract_program_keywords(context, top_k=30)

    hits = [k for k in kws if k in tl]
    missing = [k for k in kws if k not in tl]

    score = min(100, int(len(hits) * (100 / max(1, len(kws)))))

    return {
        "program_fit_score": score,
        "matched_keywords": hits[:25],
        "missing_keywords": missing[:25],
        "keywords_used": kws
    }


# =========================
# ATS RESUME SCORING (PROGRAM-SPECIFIC)
# =========================
ACTION_VERBS = [
    "led","developed","implemented","designed","built","optimized","created",
    "managed","analyzed","improved","increased","reduced","delivered","automated",
    "coordinated","executed","launched","engineered","refactored","deployed","integrated"
]

def ats_score(text: str, context: str, fmt: dict) -> dict:
    tl = text.lower()
    program_keywords = extract_program_keywords(context, top_k=30)

    section_score = 0
    section_score += 10 if fmt["section_checks"].get("resume_header") else 0
    section_score += 15 if fmt["section_checks"].get("resume_education") else 0
    section_score += 15 if fmt["section_checks"].get("resume_experience") else 0
    section_score += 10 if fmt["section_checks"].get("resume_skills") else 0
    section_score += 5  if fmt["section_checks"].get("resume_projects") else 0
    section_score = min(section_score, 50)

    verb_count = sum(1 for v in ACTION_VERBS if v in tl)
    verb_score = min(15, verb_count * 2)

    metrics = len(re.findall(r"\b\d+(\.\d+)?\s*(%|x|yrs|years|months|users|clients|requests|ms|s)\b", tl))
    metric_score = min(15, metrics * 5)

    bullets = len(re.findall(r"(\n\s*[-•*]\s+)", text))
    bullet_score = min(10, bullets)

    prog_hits = sum(1 for k in program_keywords if k in tl)
    prog_kw_score = min(20, prog_hits * 2)

    total = int(min(100, section_score + verb_score + metric_score + bullet_score + prog_kw_score))

    suggestions = []
    if not fmt["section_checks"].get("resume_projects"):
        suggestions.append("Add a 'Projects' section with 2–3 program-relevant projects (2–4 bullets each).")
    if metrics == 0:
        suggestions.append("Add measurable impact (%, time saved, scale, users, requests) in bullets.")
    if verb_count < 4:
        suggestions.append("Start bullets with strong action verbs (Developed, Implemented, Optimized, Led).")
    if bullets < 5:
        suggestions.append("Convert paragraphs into concise bullet points (ATS prefers bullets).")
    if prog_hits < 4:
        suggestions.append("Add program-specific keywords and technical skills aligned with the selected program.")

    return {
        "ats_score": total,
        "breakdown": {
            "section_score": section_score,
            "action_verbs": {"count": verb_count, "score": verb_score},
            "metrics": {"count": metrics, "score": metric_score},
            "bullets": {"count": bullets, "score": bullet_score},
            "program_keywords": {"hits": prog_hits, "score": prog_kw_score, "sample": program_keywords[:12]},
        },
        "suggestions": suggestions
    }


# =========================
# LLM EVALUATION + REWRITE
# =========================
def evaluate_and_rewrite(
    text,
    corrected,
    doc_type,
    format_report,
    grammar_report,
    context,
    program_fit,
    uni_name,
    prog_name,
    ats_report=None
):
    if doc_type == "RESUME":
        structure_rules = """
STRICT RESUME RULES:
- MUST be ATS-friendly.
- Use EXACT headings (in order):
  NAME + CONTACT
  PROFESSIONAL SUMMARY
  SKILLS (must be aligned to target program)
  EXPERIENCE
  EDUCATION
  PROJECTS (MUST ADD if missing; use [ADD DETAIL] if needed)
  ADDITIONAL (optional)
- Experience & Projects MUST be bullet points.
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten resume MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""
    else:
        structure_rules = """
STRICT SOP RULES:
- Use EXACT headings (in order):
  Introduction
  Academic Background
  Experience and Projects
  Why This Program
  Why This University
  Career Goals
  Conclusion
- No bullet lists (use paragraphs).
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten SOP MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""

    ats_block = ""
    if ats_report is not None:
        ats_block = f"\nATS_REPORT:\n{json.dumps(ats_report, ensure_ascii=False)}\n"

    # FIX 5: Pass grammar_quality_score (0-100) to LLM, not raw issue count
    grammar_summary = {
        "issue_count": grammar_report["count"],
        "quality_score_0_to_100": grammar_report["grammar_quality_score"],
        "top_issues": [i["message"] for i in grammar_report["issues"][:10]]
    }

    prompt = f"""
You are an admissions reviewer and writing coach.

Return ONLY valid JSON. No markdown. No triple backticks.

TARGET UNIVERSITY: {uni_name}
TARGET PROGRAM: {prog_name}

{structure_rules}

UNIVERSITY+PROGRAM CONTEXT (from dataset):
{context}

PROGRAM_FIT (keyword-based):
{json.dumps(program_fit, ensure_ascii=False)}

FORMAT_REPORT (rule-based):
{json.dumps(format_report, ensure_ascii=False)}

GRAMMAR_REPORT:
{json.dumps(grammar_summary, ensure_ascii=False)}
{ats_block}

DOCUMENT (grammar-corrected):
{corrected[:12000]}

Return JSON in this exact schema (match keys exactly):

{{
  "doc_type": "{doc_type}",
  "overall_score": 0,
  "overall_quality_label": "Very Weak|Weak|Average|Strong|Exceptional",

  "program_specificity": {{
    "target_university": "{uni_name}",
    "target_program": "{prog_name}",
    "fit_score": 0,
    "missing_keywords_to_add": [],
    "where_to_add_keywords": []
  }},

  "format_and_sections": {{
    "is_correct_format": false,
    "missing_sections": [],
    "section_checks": {{}}
  }},

  "grammar": {{
    "score": 0,
    "top_issues": []
  }},

  "clarity": {{
    "score": 0,
    "issues": []
  }},

  "tone": {{
    "summary": "",
    "is_appropriate": true,
    "issues": []
  }},

  "relevance_to_selected_program": {{
    "score": 0,
    "issues": [],
    "what_to_add_based_on_context": []
  }},

  "strengths": [],
  "weaknesses": [],

  "sentence_level_improvements": [
    {{
      "original": "",
      "improved": "",
      "why": ""
    }}
  ],

  "rewrite_output": {{
    "improved_document": ""
  }},

  "action_plan_next_revision": []
}}
"""
    out = ask_llm_json(prompt, max_tokens=3200, temperature=0.0)

    if isinstance(out, dict) and "error" not in out:
        # Inject rule-based format checks so they don't drift
        out.setdefault("format_and_sections", {})
        out["format_and_sections"]["is_correct_format"] = format_report["is_correct_format"]
        out["format_and_sections"]["missing_sections"] = format_report["missing_sections"]
        out["format_and_sections"]["section_checks"] = format_report["section_checks"]

        # Inject program fit as baseline
        out.setdefault("program_specificity", {})
        out["program_specificity"]["target_university"] = uni_name
        out["program_specificity"]["target_program"] = prog_name
        out["program_specificity"]["fit_score"] = program_fit.get("program_fit_score", 0)
        out["program_specificity"]["missing_keywords_to_add"] = program_fit.get("missing_keywords", [])[:12]

        # FIX 6: Override grammar score with our computed quality score so it's consistent
        out.setdefault("grammar", {})
        out["grammar"]["score"] = grammar_report["grammar_quality_score"]
        out["grammar"]["issue_count"] = grammar_report["count"]

    return out


# =========================
# SAVE OUTPUT
# FIX 7: Save full structured report + rewrite in one readable file
# =========================
def save_output(result: dict, out_path: str = "improved_document.txt"):
    lines = []

    ev = result.get("evaluation", {})
    doc_type = result.get("classification", {}).get("doc_type", "DOCUMENT")

    lines.append("=" * 60)
    lines.append(f"  DOCUMENT ANALYSIS REPORT — {doc_type}")
    lines.append("=" * 60)

    # Scores summary
    lines.append("\n📊 SCORES SUMMARY")
    lines.append("-" * 40)
    lines.append(f"  Overall Score      : {ev.get('overall_score', 'N/A')} / 100")
    lines.append(f"  Quality Label      : {ev.get('overall_quality_label', 'N/A')}")

    grammar = ev.get("grammar", {})
    lines.append(f"  Grammar Score      : {grammar.get('score', 'N/A')} / 100  ({result['grammar']['count']} issues found)")

    prog_spec = ev.get("program_specificity", {})
    lines.append(f"  Program Fit Score  : {prog_spec.get('fit_score', 'N/A')} / 100")

    if result.get("ats_score"):
        lines.append(f"  ATS Score          : {result['ats_score']['ats_score']} / 100")

    clarity = ev.get("clarity", {})
    lines.append(f"  Clarity Score      : {clarity.get('score', 'N/A')} / 100")

    relevance = ev.get("relevance_to_selected_program", {})
    lines.append(f"  Program Relevance  : {relevance.get('score', 'N/A')} / 100")

    # Format
    lines.append("\n📋 FORMAT CHECK")
    lines.append("-" * 40)
    fmt = ev.get("format_and_sections", {})
    lines.append(f"  Correct Format     : {fmt.get('is_correct_format', 'N/A')}")
    missing = fmt.get("missing_sections", [])
    lines.append(f"  Missing Sections   : {missing if missing else 'None'}")

    # Strengths / Weaknesses
    lines.append("\n✅ STRENGTHS")
    lines.append("-" * 40)
    for s in ev.get("strengths", []) or ["None identified"]:
        lines.append(f"  • {s}")

    lines.append("\n❌ WEAKNESSES")
    lines.append("-" * 40)
    for w in ev.get("weaknesses", []) or ["None identified"]:
        lines.append(f"  • {w}")

    # Grammar issues
    lines.append("\n🔤 TOP GRAMMAR ISSUES")
    lines.append("-" * 40)
    for issue in grammar.get("top_issues", [])[:5]:
        lines.append(f"  • {issue}")

    # Keywords
    lines.append("\n🔑 MISSING PROGRAM KEYWORDS")
    lines.append("-" * 40)
    missing_kws = prog_spec.get("missing_keywords_to_add", [])
    lines.append(f"  {', '.join(missing_kws) if missing_kws else 'None'}")
    lines.append(f"  Add in: {', '.join(prog_spec.get('where_to_add_keywords', []))}")

    # ATS suggestions
    if result.get("ats_score"):
        lines.append("\n🤖 ATS SUGGESTIONS")
        lines.append("-" * 40)
        for sug in result["ats_score"].get("suggestions", []):
            lines.append(f"  • {sug}")

    # Sentence improvements
    lines.append("\n✏️  SENTENCE-LEVEL IMPROVEMENTS")
    lines.append("-" * 40)
    for imp in (ev.get("sentence_level_improvements") or [])[:5]:
        if imp.get("original"):
            lines.append(f"  BEFORE : {imp['original']}")
            lines.append(f"  AFTER  : {imp['improved']}")
            lines.append(f"  WHY    : {imp['why']}")
            lines.append("")

    # Action plan
    lines.append("\n📌 ACTION PLAN FOR NEXT REVISION")
    lines.append("-" * 40)
    for step in (ev.get("action_plan_next_revision") or []):
        lines.append(f"  • {step}")

    # Rewritten document
    lines.append("\n" + "=" * 60)
    lines.append("  REWRITTEN DOCUMENT")
    lines.append("=" * 60 + "\n")

    improved = ""
    ro = ev.get("rewrite_output", {})
    if isinstance(ro, dict):
        improved = ro.get("improved_document", "") or ""

    if isinstance(improved, str):
        s = improved.strip()
        try:
            parsed = json.loads(s)
            if isinstance(parsed, dict):
                parts = []
                for k, v in parsed.items():
                    parts.append(k.upper())
                    parts.append("-" * len(k))
                    parts.append("")
                    parts.append(str(v))
                    parts.append("\n")
                improved = "\n".join(parts).strip()
        except:
            pass

    lines.append(improved.strip() if improved.strip() else "No rewrite generated.")

    full_output = "\n".join(lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(full_output)

    print(f"✅ Saved report to: {out_path}")
    # NOTE: intentionally no return value — returning the string caused notebooks
    # to print the raw repr (with escaped \n) as the cell's last expression output.


# =========================
# PRINT SUMMARY (clean terminal output)
# FIX 8: Clean summary print — no truncated JSON dumps
# =========================
def print_summary(result: dict):
    ev = result.get("evaluation", {})
    classification = result.get("classification", {})

    print("\n" + "=" * 55)
    print(f"  ANALYSIS SUMMARY")
    print("=" * 55)
    print(f"  Doc Type      : {classification.get('doc_type')}  (confidence: {classification.get('confidence')})")
    print(f"  Overall Score : {ev.get('overall_score', 'N/A')} / 100  [{ev.get('overall_quality_label', '')}]")
    print(f"  Grammar       : {result['grammar']['grammar_quality_score']} / 100  ({result['grammar']['count']} issues)")
    print(f"  Program Fit   : {result['program_fit']['program_fit_score']} / 100")

    if result.get("ats_score"):
        print(f"  ATS Score     : {result['ats_score']['ats_score']} / 100")

    fmt = result.get("format", {})
    missing_sections = fmt.get("missing_sections", [])
    print(f"  Missing Sects : {missing_sections if missing_sections else 'None'}")

    missing_kws = result["program_fit"].get("missing_keywords", [])[:8]
    print(f"  Missing KWs   : {missing_kws}")

    print("\n  Weaknesses:")
    for w in (ev.get("weaknesses") or []):
        print(f"    • {w}")

    if result.get("ats_score"):
        print("\n  ATS Suggestions:")
        for s in result["ats_score"].get("suggestions", []):
            print(f"    • {s}")

    print("=" * 55 + "\n")


# =========================
# MAIN PIPELINE
# =========================
def analyze(doc, uni, prog, uni_csv, prog_csv):
    text = read_document(doc)

    grammar = grammar_check(text)
    classification = classify(text)
    doc_type = classification.get("doc_type", "SOP")

    fmt = format_check(text, doc_type)

    unis, progs = load_data(uni_csv, prog_csv)
    uni_index = build_index(unis, "combined", UNI_EMB_PKL)
    prog_index = build_index(progs, "combined", PROG_EMB_PKL)

    context = build_context(unis, progs, uni_index, prog_index, uni, prog)

    prog_fit = program_fit_score(text, context)

    ats = None
    if doc_type == "RESUME":
        ats = ats_score(text, context, fmt)

    evaluation = evaluate_and_rewrite(
        text=text,
        corrected=grammar["corrected"],
        doc_type=doc_type,
        format_report=fmt,
        grammar_report=grammar,
        context=context,
        program_fit=prog_fit,
        uni_name=uni,
        prog_name=prog,
        ats_report=ats
    )

    return {
        "classification": classification,
        "grammar": grammar,
        "format": fmt,
        "program_fit": prog_fit,
        "ats_score": ats,
        "evaluation": evaluation
    }


print("✅ Ready: Fixed Program-specific Analyzer (SOP + Resume)")
print("   Fixes: URL noise in keywords | Grammar score (0-100) | Doc-type-only section checks | Clean report output")

# ── Run this cell after your Groq setup cell ──────────────────────────────────
import json

result = analyze(
    doc="input.pdf",
    uni="Boston University",
    prog="Computer Science",
    uni_csv="universities_profile_filled (1).csv",
    prog_csv="program_Scrape.csv"
)

# Clean summary printed to terminal
print_summary(result)

# Save full structured report + rewrite to file (no return value — avoids raw \n repr in notebook)
save_output(result, "improved_document.txt")

import os, re, json, pickle
import numpy as np
import pandas as pd

from pypdf import PdfReader
import docx
import language_tool_python

from sentence_transformers import SentenceTransformer
import faiss


# ==========================================================
# IMPORTANT: GROQ SETUP IS IN YOUR OTHER CELL
# This code expects:
#   - a global variable named `client`
#   - model name in `LLM_MODEL`
# Example in your Groq cell:
#   from groq import Groq
#   client = Groq(api_key=os.environ["GROQ_API_KEY"])
#   LLM_MODEL = "llama-3.3-70b-versatile"
# ==========================================================

# =========================
# CONFIG
# =========================
EMBED_MODEL = "all-MiniLM-L6-v2"
UNI_EMB_PKL = "uni_embeddings.pkl"
PROG_EMB_PKL = "program_embeddings.pkl"

embedder = SentenceTransformer(EMBED_MODEL)
lt_tool = language_tool_python.LanguageTool("en-US")

# FIX 1: Expanded stoplist to remove URL fragments, noise, and generic words
KEYWORD_STOPLIST = {
    # Generic words
    "the","and","for","with","this","that","from","your","have","will","you","our","are","can","also",
    "program","university","department","students","course","courses","study","research","faculty",
    "requirements","requirement","application","admission","deadline","tuition","fees","location",
    "more","information","please","visit","contact","email","phone","address","apply","online",
    "full","time","part","per","year","credit","hours","minimum","maximum","based","must","meet",
    "all","any","one","two","three","four","five","six","seven","eight","nine","ten",
    "not","but","its","has","was","been","they","their","them","who","what","when","where","how",
    "each","which","about","after","before","during","other","into","than","then","some","only",
    "may","use","used","new","also","both","well","even","such","same","most","many","best",
    # URL fragments — FIX for "http", "https", "www", "adance" etc.
    "http","https","www","html","php","asp","aspx","edu","com","org","net","gov","htm",
    # Common garbage tokens from scraped CSV data
    "nan","none","null","true","false","yes","no",
    # Known garbage tokens observed in scraped CSV output
    "rolling","adance","january","advancedcomputinginstitute","institute","private","college",
    "academics","programs","computing","public",  # too generic to be useful signal
}


# =========================
# SAFE JSON PARSE
# =========================
def safe_json_parse(text: str) -> dict:
    if text is None:
        return {"error": "empty_response"}

    t = text.strip()

    # Remove markdown fences if present
    if t.startswith("```"):
        t = re.sub(r"^```[a-zA-Z]*\s*", "", t)
        t = re.sub(r"\s*```$", "", t).strip()

    # Try direct JSON
    try:
        return json.loads(t)
    except:
        # Try to isolate the first JSON object
        m = re.search(r"\{.*\}", t, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except:
                pass

    return {"error": "invalid_json", "raw": text[:4000]}


# =========================
# LLM CALL (expects global `client`, `LLM_MODEL`)
# =========================
def ask_llm_json(prompt: str, max_tokens: int = 2500, temperature: float = 0.0) -> dict:
    if "client" not in globals():
        raise RuntimeError("Groq client not found. Define `client = Groq(...)` in a separate cell first.")
    if "LLM_MODEL" not in globals():
        raise RuntimeError("LLM_MODEL not found. Define `LLM_MODEL = ...` in your Groq cell first.")

    r = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        max_tokens=max_tokens
    )
    return safe_json_parse(r.choices[0].message.content)


# =========================
# READ DOCUMENT
# =========================
def read_pdf(path: str) -> str:
    reader = PdfReader(path)
    return "\n".join([(p.extract_text() or "") for p in reader.pages]).strip()

def read_docx(path: str) -> str:
    d = docx.Document(path)
    return "\n".join([p.text for p in d.paragraphs]).strip()

def read_txt(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

def read_document(path: str) -> str:
    ext = os.path.splitext(path)[1].lower()
    if ext == ".pdf":
        return read_pdf(path)
    if ext == ".docx":
        return read_docx(path)
    if ext == ".txt":
        return read_txt(path)
    raise ValueError("Unsupported file type (.pdf/.docx/.txt)")


# =========================
# LOAD + EMBEDDINGS + FAISS
# =========================
def load_data(university_csv: str, program_csv: str):
    unis = pd.read_csv(university_csv)
    progs = pd.read_csv(program_csv)

    unis["combined"] = unis.fillna("").astype(str).agg(" | ".join, axis=1)
    progs["combined"] = progs.fillna("").astype(str).agg(" | ".join, axis=1)

    return unis, progs

def build_index(df: pd.DataFrame, text_col: str, pkl_path: str):
    texts = df[text_col].fillna("").astype(str).tolist()

    if os.path.exists(pkl_path):
        with open(pkl_path, "rb") as f:
            emb = pickle.load(f)
        emb = np.array(emb, dtype="float32")
    else:
        emb = embedder.encode(texts, normalize_embeddings=True)
        emb = np.array(emb, dtype="float32")
        with open(pkl_path, "wb") as f:
            pickle.dump(emb, f)

    index = faiss.IndexFlatIP(emb.shape[1])
    index.add(emb)
    return index

def retrieve(df: pd.DataFrame, index, query: str, k: int = 3) -> pd.DataFrame:
    q = embedder.encode([query], normalize_embeddings=True).astype("float32")
    D, I = index.search(q, k)
    out = df.iloc[I[0]].copy()
    out["score"] = D[0]
    return out


# =========================
# GRAMMAR CHECK
# =========================
def grammar_check(text: str, max_issues: int = 25) -> dict:
    matches = lt_tool.check(text)
    corrected = language_tool_python.utils.correct(text, matches)

    issues = []
    for m in matches[:max_issues]:
        issues.append({
            "message": m.message,
            "context": m.context,
            "replacements": m.replacements[:5]
        })

    # FIX 2: Compute a 0-100 grammar quality score (higher = fewer issues, better quality)
    # Penalise ~2 points per issue, floor at 0
    issue_count = len(matches)
    grammar_quality_score = max(0, 100 - issue_count * 2)

    return {
        "count": issue_count,                        # raw issue count (e.g. 22)
        "grammar_quality_score": grammar_quality_score,  # 0-100 quality score (e.g. 56)
        "issues": issues,
        "corrected": corrected
    }


# =========================
# CLASSIFY DOC TYPE (LLM)
# =========================
def classify(text: str) -> dict:
    prompt = f"""
Return ONLY JSON.

Schema:
{{
  "doc_type":"SOP|RESUME",
  "confidence": 0.0,
  "reason_short":""
}}

TEXT:
{text[:6000]}
"""
    out = ask_llm_json(prompt, max_tokens=450)

    if "doc_type" not in out:
        out = {"doc_type": "RESUME" if "experience" in text.lower() else "SOP", "confidence": 0.5, "reason_short": "fallback"}
    return out


# =========================
# FORMAT CHECK
# FIX 3: Only evaluate sections relevant to the detected doc_type
# =========================
def format_check(text: str, doc_type: str) -> dict:
    lower = text.lower()
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    first_para = lines[0] if lines else ""

    checks = {}

    if doc_type == "RESUME":
        # Only check resume sections for a RESUME doc
        checks["resume_header"]     = bool(re.search(r"\bemail\b|@\w+|\bphone\b|\bmobile\b|\blinkedin\b|\bgithub\b", text, re.I))
        checks["resume_education"]  = bool(re.search(r"\beducation\b|\bdegree\b|\buniversity\b|\bcgpa\b|\bgpa\b", text, re.I))
        checks["resume_experience"] = bool(re.search(r"\bexperience\b|\bemployment\b|\bwork history\b", text, re.I))
        checks["resume_projects"]   = bool(re.search(r"\bprojects?\b|\bportfolio\b", text, re.I))
        checks["resume_skills"]     = bool(re.search(r"\bskills?\b|\btechnologies\b|\btools\b", text, re.I))
        checks["resume_extras"]     = bool(re.search(r"\bcertifications?\b|\bawards?\b|\bvolunteer\b|\bleadership\b", text, re.I))

        required = ["resume_header", "resume_education", "resume_experience", "resume_skills"]

    else:
        # Only check SOP sections for an SOP doc
        # broad intro: any meaningful opening (passionate, motivated, or paragraph > 50 chars)
        checks["sop_intro"] = (
            "statement of purpose" in lower
            or "i am applying" in lower
            or "i wish to pursue" in lower
            or "i am excited" in lower
            or "i am interested" in lower
            or bool(re.search(r"\b(passionate|motivated|aspiring|enthusiastic|as a)\b", lower))
            or len(first_para) > 50
        )
        checks["sop_academics"]      = bool(re.search(r"\b(bachelor|undergraduate|degree|cgpa|gpa|university|graduation|college)\b", lower))
        checks["sop_experience"]     = bool(re.search(r"\b(intern|internship|project|research|work experience|worked|employment)\b", lower))
        checks["sop_why_program"]    = bool(re.search(r"\b(program|curriculum|courses|specialization|research interests|master)\b", lower))
        checks["sop_why_university"] = bool(re.search(r"\b(university|faculty|lab|research group|department|campus|institution)\b", lower))
        # broader goals: future tense, intentions, career mentions
        checks["sop_goals"] = bool(re.search(
            r"\b(career goals?|short[- ]term|long[- ]term|i aim to|i plan to|aspire|i hope to|i intend|my goal|after (completing|graduation)|future)\b",
            lower
        ))
        checks["sop_conclusion"] = bool(re.search(
            r"\b(in conclusion|thank you|i look forward|i would be honored|i am confident|i believe|i hope to|i am eager)\b",
            lower
        ))

        required = ["sop_intro", "sop_academics", "sop_experience", "sop_goals"]

    missing = [r for r in required if not checks.get(r)]

    # Also flag optional-but-important missing sections
    if doc_type == "RESUME" and not checks.get("resume_projects"):
        missing.append("resume_projects")
    if doc_type == "SOP" and not checks.get("sop_conclusion"):
        missing.append("sop_conclusion")

    return {
        "is_correct_format": (len(missing) == 0),
        "missing_sections": missing,
        "section_checks": checks
    }


# =========================
# CONTEXT BUILDER
# =========================
def build_context(unis, progs, uni_index, prog_index, uni, prog):
    q = f"{uni} {prog}".strip()
    u = retrieve(unis, uni_index, q, k=3)
    p = retrieve(progs, prog_index, q, k=3)
    return "\n".join(list(u["combined"]) + list(p["combined"]))


# =========================
# PROGRAM KEYWORDS (FROM CONTEXT)
# FIX 4: Strip URLs and noise tokens before ranking keywords
# =========================
def extract_program_keywords(context: str, top_k: int = 30) -> list:
    # Remove full URLs first so fragments like "adance" from "advancedcomputinginstitute" don't slip through
    context_clean = re.sub(r"https?://\S+", " ", context)
    context_clean = re.sub(r"www\.\S+", " ", context_clean)

    # Extract only alphabetic tokens of length >= 4 (avoids "www", "http", 3-letter noise)
    words = re.findall(r"[a-zA-Z]{4,}", context_clean.lower())

    # Filter against expanded stoplist
    words = [w for w in words if w not in KEYWORD_STOPLIST and not w.isdigit()]

    freq = {}
    for w in words:
        freq[w] = freq.get(w, 0) + 1

    # Only keep words that appear at least twice — filters one-off garbage tokens
    freq = {w: c for w, c in freq.items() if c >= 2}

    sorted_words = sorted(freq.items(), key=lambda x: x[1], reverse=True)
    return [w for w, _ in sorted_words[:top_k]]


def program_fit_score(text: str, context: str) -> dict:
    tl = text.lower()
    kws = extract_program_keywords(context, top_k=30)

    hits = [k for k in kws if k in tl]
    missing = [k for k in kws if k not in tl]

    score = min(100, int(len(hits) * (100 / max(1, len(kws)))))

    return {
        "program_fit_score": score,
        "matched_keywords": hits[:25],
        "missing_keywords": missing[:25],
        "keywords_used": kws
    }


# =========================
# ATS RESUME SCORING (PROGRAM-SPECIFIC)
# =========================
ACTION_VERBS = [
    "led","developed","implemented","designed","built","optimized","created",
    "managed","analyzed","improved","increased","reduced","delivered","automated",
    "coordinated","executed","launched","engineered","refactored","deployed","integrated"
]

def ats_score(text: str, context: str, fmt: dict) -> dict:
    tl = text.lower()
    program_keywords = extract_program_keywords(context, top_k=30)

    section_score = 0
    section_score += 10 if fmt["section_checks"].get("resume_header") else 0
    section_score += 15 if fmt["section_checks"].get("resume_education") else 0
    section_score += 15 if fmt["section_checks"].get("resume_experience") else 0
    section_score += 10 if fmt["section_checks"].get("resume_skills") else 0
    section_score += 5  if fmt["section_checks"].get("resume_projects") else 0
    section_score = min(section_score, 50)

    verb_count = sum(1 for v in ACTION_VERBS if v in tl)
    verb_score = min(15, verb_count * 2)

    metrics = len(re.findall(r"\b\d+(\.\d+)?\s*(%|x|yrs|years|months|users|clients|requests|ms|s)\b", tl))
    metric_score = min(15, metrics * 5)

    bullets = len(re.findall(r"(\n\s*[-•*]\s+)", text))
    bullet_score = min(10, bullets)

    prog_hits = sum(1 for k in program_keywords if k in tl)
    prog_kw_score = min(20, prog_hits * 2)

    total = int(min(100, section_score + verb_score + metric_score + bullet_score + prog_kw_score))

    suggestions = []
    if not fmt["section_checks"].get("resume_projects"):
        suggestions.append("Add a 'Projects' section with 2–3 program-relevant projects (2–4 bullets each).")
    if metrics == 0:
        suggestions.append("Add measurable impact (%, time saved, scale, users, requests) in bullets.")
    if verb_count < 4:
        suggestions.append("Start bullets with strong action verbs (Developed, Implemented, Optimized, Led).")
    if bullets < 5:
        suggestions.append("Convert paragraphs into concise bullet points (ATS prefers bullets).")
    if prog_hits < 4:
        suggestions.append("Add program-specific keywords and technical skills aligned with the selected program.")

    return {
        "ats_score": total,
        "breakdown": {
            "section_score": section_score,
            "action_verbs": {"count": verb_count, "score": verb_score},
            "metrics": {"count": metrics, "score": metric_score},
            "bullets": {"count": bullets, "score": bullet_score},
            "program_keywords": {"hits": prog_hits, "score": prog_kw_score, "sample": program_keywords[:12]},
        },
        "suggestions": suggestions
    }


# =========================
# LLM EVALUATION + REWRITE
# =========================
def evaluate_and_rewrite(
    text,
    corrected,
    doc_type,
    format_report,
    grammar_report,
    context,
    program_fit,
    uni_name,
    prog_name,
    ats_report=None
):
    if doc_type == "RESUME":
        structure_rules = """
STRICT RESUME RULES:
- MUST be ATS-friendly.
- Use EXACT headings (in order):
  NAME + CONTACT
  PROFESSIONAL SUMMARY
  SKILLS (must be aligned to target program)
  EXPERIENCE
  EDUCATION
  PROJECTS (MUST ADD if missing; use [ADD DETAIL] if needed)
  ADDITIONAL (optional)
- Experience & Projects MUST be bullet points.
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten resume MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""
    else:
        structure_rules = """
STRICT SOP RULES:
- Use EXACT headings (in order):
  Introduction
  Academic Background
  Experience and Projects
  Why This Program
  Why This University
  Career Goals
  Conclusion
- No bullet lists (use paragraphs).
- Do NOT invent facts. Use [ADD DETAIL] if missing.
- Output MUST be valid JSON only.
- The full rewritten SOP MUST be inside rewrite_output.improved_document as PLAIN TEXT (not JSON).
"""

    ats_block = ""
    if ats_report is not None:
        ats_block = f"\nATS_REPORT:\n{json.dumps(ats_report, ensure_ascii=False)}\n"

    # FIX 5: Pass grammar_quality_score (0-100) to LLM, not raw issue count
    grammar_summary = {
        "issue_count": grammar_report["count"],
        "quality_score_0_to_100": grammar_report["grammar_quality_score"],
        "top_issues": [i["message"] for i in grammar_report["issues"][:10]]
    }

    prompt = f"""
You are an admissions reviewer and writing coach.

Return ONLY valid JSON. No markdown. No triple backticks.

TARGET UNIVERSITY: {uni_name}
TARGET PROGRAM: {prog_name}

{structure_rules}

UNIVERSITY+PROGRAM CONTEXT (from dataset):
{context}

PROGRAM_FIT (keyword-based):
{json.dumps(program_fit, ensure_ascii=False)}

FORMAT_REPORT (rule-based):
{json.dumps(format_report, ensure_ascii=False)}

GRAMMAR_REPORT:
{json.dumps(grammar_summary, ensure_ascii=False)}
{ats_block}

DOCUMENT (grammar-corrected):
{corrected[:12000]}

Return JSON in this exact schema (match keys exactly):

{{
  "doc_type": "{doc_type}",
  "overall_score": 0,
  "overall_quality_label": "Very Weak|Weak|Average|Strong|Exceptional",

  "program_specificity": {{
    "target_university": "{uni_name}",
    "target_program": "{prog_name}",
    "fit_score": 0,
    "missing_keywords_to_add": [],
    "where_to_add_keywords": []
  }},

  "format_and_sections": {{
    "is_correct_format": false,
    "missing_sections": [],
    "section_checks": {{}}
  }},

  "grammar": {{
    "score": 0,
    "top_issues": []
  }},

  "clarity": {{
    "score": 0,
    "issues": []
  }},

  "tone": {{
    "summary": "",
    "is_appropriate": true,
    "issues": []
  }},

  "relevance_to_selected_program": {{
    "score": 0,
    "issues": [],
    "what_to_add_based_on_context": []
  }},

  "strengths": [],
  "weaknesses": [],

  "sentence_level_improvements": [
    {{
      "original": "",
      "improved": "",
      "why": ""
    }}
  ],

  "rewrite_output": {{
    "improved_document": ""
  }},

  "action_plan_next_revision": []
}}
"""
    out = ask_llm_json(prompt, max_tokens=3200, temperature=0.0)

    if isinstance(out, dict) and "error" not in out:
        # Inject rule-based format checks so they don't drift
        out.setdefault("format_and_sections", {})
        out["format_and_sections"]["is_correct_format"] = format_report["is_correct_format"]
        out["format_and_sections"]["missing_sections"] = format_report["missing_sections"]
        out["format_and_sections"]["section_checks"] = format_report["section_checks"]

        # Inject program fit as baseline
        out.setdefault("program_specificity", {})
        out["program_specificity"]["target_university"] = uni_name
        out["program_specificity"]["target_program"] = prog_name
        out["program_specificity"]["fit_score"] = program_fit.get("program_fit_score", 0)
        out["program_specificity"]["missing_keywords_to_add"] = program_fit.get("missing_keywords", [])[:12]

        # Fix: Override grammar score with our computed quality score so it's consistent
        out.setdefault("grammar", {})
        out["grammar"]["score"] = grammar_report["grammar_quality_score"]
        out["grammar"]["issue_count"] = grammar_report["count"]

        # Fix 4: Enforce quality label from overall_score — never trust LLM label alone
        score = out.get("overall_score", 0)
        if score >= 85:
            label = "Exceptional"
        elif score >= 70:
            label = "Strong"
        elif score >= 50:
            label = "Average"
        elif score >= 30:
            label = "Weak"
        else:
            label = "Very Weak"
        out["overall_quality_label"] = label

        # Fix: Add note if program fit is 0 (unrelated document)
        if program_fit.get("program_fit_score", 0) == 0:
            out.setdefault("program_specificity", {})
            out["program_specificity"]["note"] = (
                "Document content appears unrelated to the target program. "
                "No program-specific keywords were found."
            )

    return out


# =========================
# SAVE OUTPUT
# FIX 7: Save full structured report + rewrite in one readable file
# =========================
def save_output(result: dict, out_path: str = "improved_document.txt"):
    lines = []

    ev = result.get("evaluation", {})
    doc_type = result.get("classification", {}).get("doc_type", "DOCUMENT")

    lines.append("=" * 60)
    lines.append(f"  DOCUMENT ANALYSIS REPORT — {doc_type}")
    lines.append("=" * 60)

    # Scores summary
    lines.append("\n📊 SCORES SUMMARY")
    lines.append("-" * 40)
    lines.append(f"  Overall Score      : {ev.get('overall_score', 'N/A')} / 100")
    lines.append(f"  Quality Label      : {ev.get('overall_quality_label', 'N/A')}")

    grammar = ev.get("grammar", {})
    lines.append(f"  Grammar Score      : {grammar.get('score', 'N/A')} / 100  ({result['grammar']['count']} issues found)")

    prog_spec = ev.get("program_specificity", {})
    prog_fit_val = result["program_fit"]["program_fit_score"]
    fit_suffix = "  ⚠️  Document appears unrelated to target program." if prog_fit_val == 0 else ""
    lines.append(f"  Program Fit Score  : {prog_fit_val} / 100{fit_suffix}")

    if result.get("ats_score"):
        lines.append(f"  ATS Score          : {result['ats_score']['ats_score']} / 100")

    clarity = ev.get("clarity", {})
    lines.append(f"  Clarity Score      : {clarity.get('score', 'N/A')} / 100")

    relevance = ev.get("relevance_to_selected_program", {})
    lines.append(f"  Program Relevance  : {relevance.get('score', 'N/A')} / 100")

    # Format
    lines.append("\n📋 FORMAT CHECK")
    lines.append("-" * 40)
    fmt = ev.get("format_and_sections", {})
    lines.append(f"  Correct Format     : {fmt.get('is_correct_format', 'N/A')}")
    missing = fmt.get("missing_sections", [])
    lines.append(f"  Missing Sections   : {missing if missing else 'None'}")

    # Strengths / Weaknesses
    lines.append("\n✅ STRENGTHS")
    lines.append("-" * 40)
    for s in ev.get("strengths", []) or ["None identified"]:
        lines.append(f"  • {s}")

    lines.append("\n❌ WEAKNESSES")
    lines.append("-" * 40)
    for w in ev.get("weaknesses", []) or ["None identified"]:
        lines.append(f"  • {w}")

    # Grammar issues
    lines.append("\n🔤 TOP GRAMMAR ISSUES")
    lines.append("-" * 40)
    for issue in grammar.get("top_issues", [])[:5]:
        lines.append(f"  • {issue}")

    # Keywords
    lines.append("\n🔑 MISSING PROGRAM KEYWORDS")
    lines.append("-" * 40)
    missing_kws = prog_spec.get("missing_keywords_to_add", [])
    lines.append(f"  {', '.join(missing_kws) if missing_kws else 'None'}")
    lines.append(f"  Add in: {', '.join(prog_spec.get('where_to_add_keywords', []))}")

    # ATS suggestions
    if result.get("ats_score"):
        lines.append("\n🤖 ATS SUGGESTIONS")
        lines.append("-" * 40)
        for sug in result["ats_score"].get("suggestions", []):
            lines.append(f"  • {sug}")

    # Sentence improvements
    lines.append("\n✏️  SENTENCE-LEVEL IMPROVEMENTS")
    lines.append("-" * 40)
    for imp in (ev.get("sentence_level_improvements") or [])[:5]:
        if imp.get("original"):
            lines.append(f"  BEFORE : {imp['original']}")
            lines.append(f"  AFTER  : {imp['improved']}")
            lines.append(f"  WHY    : {imp['why']}")
            lines.append("")

    # Action plan
    lines.append("\n📌 ACTION PLAN FOR NEXT REVISION")
    lines.append("-" * 40)
    for step in (ev.get("action_plan_next_revision") or []):
        lines.append(f"  • {step}")

    # Rewritten document
    lines.append("\n" + "=" * 60)
    lines.append("  REWRITTEN DOCUMENT")
    lines.append("=" * 60 + "\n")

    improved = ""
    ro = ev.get("rewrite_output", {})
    if isinstance(ro, dict):
        improved = ro.get("improved_document", "") or ""

    if isinstance(improved, str):
        s = improved.strip()
        try:
            parsed = json.loads(s)
            if isinstance(parsed, dict):
                parts = []
                for k, v in parsed.items():
                    parts.append(k.upper())
                    parts.append("-" * len(k))
                    parts.append("")
                    parts.append(str(v))
                    parts.append("\n")
                improved = "\n".join(parts).strip()
        except:
            pass

    lines.append(improved.strip() if improved.strip() else "No rewrite generated.")

    full_output = "\n".join(lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(full_output)

    print(f"✅ Saved report to: {out_path}")
    # NOTE: intentionally no return value — returning the string caused notebooks
    # to print the raw repr (with escaped \n) as the cell's last expression output.


# =========================
# PRINT SUMMARY (clean terminal output)
# FIX 8: Clean summary print — no truncated JSON dumps
# =========================
def print_summary(result: dict):
    ev = result.get("evaluation", {})
    classification = result.get("classification", {})

    print("\n" + "=" * 55)
    print(f"  ANALYSIS SUMMARY")
    print("=" * 55)
    print(f"  Doc Type      : {classification.get('doc_type')}  (confidence: {classification.get('confidence')})")
    print(f"  Overall Score : {ev.get('overall_score', 'N/A')} / 100  [{ev.get('overall_quality_label', '')}]")
    print(f"  Grammar       : {result['grammar']['grammar_quality_score']} / 100  ({result['grammar']['count']} issues)")
    prog_fit = result["program_fit"]["program_fit_score"]
    fit_note = ""
    if prog_fit == 0:
        fit_note = "  ⚠️  Document content appears unrelated to the target program."
    print(f"  Program Fit   : {prog_fit} / 100{fit_note}")

    if result.get("ats_score"):
        print(f"  ATS Score     : {result['ats_score']['ats_score']} / 100")

    fmt = result.get("format", {})
    missing_sections = fmt.get("missing_sections", [])
    print(f"  Missing Sects : {missing_sections if missing_sections else 'None'}")

    missing_kws = result["program_fit"].get("missing_keywords", [])[:8]
    print(f"  Missing KWs   : {missing_kws}")

    print("\n  Weaknesses:")
    for w in (ev.get("weaknesses") or []):
        print(f"    • {w}")

    if result.get("ats_score"):
        print("\n  ATS Suggestions:")
        for s in result["ats_score"].get("suggestions", []):
            print(f"    • {s}")

    print("=" * 55 + "\n")


# =========================
# MAIN PIPELINE
# =========================
def analyze(doc, uni, prog, uni_csv, prog_csv):
    text = read_document(doc)

    grammar = grammar_check(text)
    classification = classify(text)
    doc_type = classification.get("doc_type", "SOP")

    fmt = format_check(text, doc_type)

    unis, progs = load_data(uni_csv, prog_csv)
    uni_index = build_index(unis, "combined", UNI_EMB_PKL)
    prog_index = build_index(progs, "combined", PROG_EMB_PKL)

    context = build_context(unis, progs, uni_index, prog_index, uni, prog)

    prog_fit = program_fit_score(text, context)

    ats = None
    if doc_type == "RESUME":
        ats = ats_score(text, context, fmt)

    evaluation = evaluate_and_rewrite(
        text=text,
        corrected=grammar["corrected"],
        doc_type=doc_type,
        format_report=fmt,
        grammar_report=grammar,
        context=context,
        program_fit=prog_fit,
        uni_name=uni,
        prog_name=prog,
        ats_report=ats
    )

    return {
        "classification": classification,
        "grammar": grammar,
        "format": fmt,
        "program_fit": prog_fit,
        "ats_score": ats,
        "evaluation": evaluation
    }


print("✅ Ready: Fixed Program-specific Analyzer (SOP + Resume)")
print("   Fixes: URL noise in keywords | Grammar score (0-100) | Doc-type-only section checks | Clean report output")

# ── Run this cell after your Groq setup cell ──────────────────────────────────
import json

result = analyze(
    doc="bad.pdf",
    uni="Boston University",
    prog="ELECTRONICS AND COMMINICATIONS  ENGINEERING",
    uni_csv="universities_profile_filled (1).csv",
    prog_csv="program_Scrape.csv"
)

# Clean summary printed to terminal
print_summary(result)

# Save full structured report + rewrite to file (no return value — avoids raw \n repr in notebook)
save_output(result, "improved_document.txt")